In [1]:
import pandas as pd
import regex
import numpy as np

In [2]:
file = r'..\data\raw\train.csv'

df = pd.read_csv(file)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)

rare_titles = ['Lady','Countess','Capt','Col','Don','Dr','Major','Rev','Sir','Jonkheer','Dona']
df["Title"] = df["Title"].replace(rare_titles, "Rare")
df["Title"] = df["Title"].replace({"Mlle":"Miss","Ms":"Miss","Mme":"Mrs"})

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\gustavo\AppData\Local\Temp\ipykernel_26372\329225020.py:1: SyntaxWarning: invalid escape sequence '\.'
  df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)

In [5]:
df['Ticket'] = df['Ticket'].str.replace(r'[^A-Za-z0-9]', '', regex=True)
df['Cabin'] = df['Cabin'].str.replace(r'[^A-Za-z0-9]', '', regex=True)

In [6]:
df['Ticket_1p'] = df['Ticket'].apply(lambda row: row[:1] if pd.notnull(row) else row)
df['Cabin_1p'] = df['Cabin'].apply(lambda row: row[:1] if pd.notnull(row) else row)

In [7]:
df['Embarked_mod'] = df['Embarked'].map({'S':'SQ', 'Q':'SQ', 'C':'C'})

In [8]:
df['SibSp_mod'] = df['SibSp'].apply(lambda row: 'yes' if row > 0 else 'no')

In [9]:
df['Fare'] = df['Fare'].apply(lambda x: np.abs(x))

In [10]:
mask = df['Survived'] == 0

df.loc[mask]['Fare'].max()

263.0

In [11]:
mask = df['Survived'] == 1

df.loc[mask]['Fare'].max()

512.3292

In [12]:
df = df.astype(
    {'Pclass':str, 'Parch':str}
)

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Ticket_1p,Cabin_1p,Embarked_mod,SibSp_mod
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A521171,7.2500,NaN,S,Mr,A,NaN,SQ,yes
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC17599,71.2833,C85,C,Mrs,P,C,C,yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STONO23101282,7.9250,NaN,S,Miss,S,NaN,SQ,no
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,1,C,SQ,yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,3,NaN,SQ,no