In [1]:
import pandas as pd
import numpy as np

In [2]:
file = r'..\data\raw\train.csv'

df = pd.read_csv(file)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)

rare_titles = ['Lady','Countess','Capt','Col','Don','Dr','Major','Rev','Sir','Jonkheer','Dona']
df["Title"] = df["Title"].replace(rare_titles, "Rare")
df["Title"] = df["Title"].replace({"Mlle":"Miss","Ms":"Miss","Mme":"Mrs"})

In [5]:
df['Ticket'] = df['Ticket'].str.replace(r'[^A-Za-z0-9]', '', regex=True)
df['Cabin'] = df['Cabin'].str.replace(r'[^A-Za-z0-9]', '', regex=True)

In [6]:
df['Ticket_1p'] = df['Ticket'].apply(lambda row: row[:1] if pd.notnull(row) else row)
df['Cabin_1p'] = df['Cabin'].apply(lambda row: row[:1] if pd.notnull(row) else row)

In [7]:
df['SibSp_mod'] = df['SibSp'].apply(lambda row: 'yes' if row > 0 else 'no')

In [8]:
df['Fare'] = df['Fare'].apply(lambda x: np.abs(x))

In [9]:
mask = df['Survived'] == 0

df.loc[mask]['Fare'].max()

263.0

In [10]:
mask = df['Survived'] == 1

df.loc[mask]['Fare'].max()

512.3292

In [11]:
df = df.astype(
    {'Pclass':str, 'Parch':str}
)

In [12]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Ticket_1p,Cabin_1p,SibSp_mod
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A521171,7.2500,NaN,S,Mr,A,NaN,yes
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC17599,71.2833,C85,C,Mrs,P,C,yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STONO23101282,7.9250,NaN,S,Miss,S,NaN,no
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,1,C,yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,3,NaN,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rare,2,NaN,no
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss,1,B,no
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,WC6607,23.4500,NaN,S,Miss,W,NaN,yes
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr,1,C,no
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr,3,NaN,no